apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'fastapi-app'
      metrics_path: '/metrics'
      scheme: http
      static_configs:
      - targets: ['fastapi-app:80']

